-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 15:39:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `company` (
  `idcompany` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NULL,
  `sigla` VARCHAR(45) NULL,
  PRIMARY KEY (`idcompany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `username` VARCHAR(45) NULL,
  `password` TEXT NULL,
  `idcompany` INT NULL,
  `level` INT NULL,
  `token` TEXT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `semus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `semus` (
  `idsemus` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NULL,
  `idcompany` INT NULL,
  `result` TEXT NULL,
  `input` TEXT NULL,
  PRIMARY KEY (`idsemus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logs` (
  `idlogs` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NULL,
  `ltime` TIMESTAMP NULL,
  `iduser` INT NULL,
  `page` TEXT NULL,
  PRIMARY KEY (`idlogs`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
